# Custom Cloudduty

foreground            #ffffff
background            #0d0f18
cursor                #839496

selection_foreground  #ffffff
selection_background  #073642

# normal
# color0                #2b2b2b
# color1                #ec7050
# color2                #8ce00a
# color3                #ffb900
# color4                #4a9fe0
# color5                #6c43a5
# color6                #00d7eb
# color7                #ffffff
color0                #444444
color1                #f43c39
color2               #aff349
color3               #ffd141
color4               #0092ff
color5               #b286f0
color6               #49fae8
color7               #ffffff

# bright
color8                #444444
color9                #eb5b58
color10               #abe05a
color11               #ffd141
color12               #0092ff
color13               #9a5feb
color14               #67ffef
color15               #ffffff
