# --- Main Colors ---
background            #131318
foreground            #e4e1e9
cursor                #e4e1e9
cursor_text_color     #131318

selection_background  #434559
selection_foreground  #e0e1f9

url_color             #e6bad7

# --- ANSI Colors ---
color0                #03040b
color1                #ba1a1a
color2                #3d55eb
color3                #c4c5dd
color4                #bbc3ff
color5                #e6bad7
color6                #c4c5dd
color7                #e4e1e9

color8                #46464f
color9                #ffdad6
color10               #5d3c54
color11               #434559
color12               #3a4279
color13               #434559
color14               #5d3c54
color15               #c7c5d0

# --- Starship Prompt Bubbles ---
color255              #3a4279
color254              #bbc3ff
color253              #434559
color252              #c4c5dd
color251              #5d3c54
color250              #e6bad7
color249              #93000a
color248              #ffb4ab

color232              #dfe0ff
color233              #232c61
color234              #e0e1f9
color235              #2d2f42
color236              #ffd7f0
color237              #45263d
color238              #ffdad6
color239              #690005
color240              #dfe0ff

# Matched with unthemed light/dark
color243              #bbc3ff
color244              #ffb4ab
color245              #46464f

# --- UI Elements ---
active_tab_foreground   #232c61
active_tab_background   #bbc3ff
inactive_tab_foreground #dfe0ff
inactive_tab_background #3a4279

active_border_color     #bbc3ff
inactive_border_color   #90909a

# --- Marks ---
mark1_foreground        #0c154b
mark1_background        #dfe0ff
mark2_foreground        #181a2c
mark2_background        #e0e1f9
mark3_foreground        #2d1227
mark3_background        #ffd7f0
