[config]

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf.template-custom'
output_path = '~/.config/kitty/themes/Matugen.conf'
# post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.neovim]
input_path = './templates/neovim.lua'
output_path = '~/.config/nvim/lua/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'
